#!/bin/sh
#dmd -profile -profile=gc -debug -gs -g -ofmain main.d helper.d objects.d viewport.d g.d -L-L. $@
dmd -profile -profile=gc -debug -gs -g -ofmain `ls ./src/*.d` -L-L./lib/ $@
echo " * deleting old trace log files because they're cumulative."
rm trace.log 2>&1 /dev/null
rm trace.def 2>&1 /dev/null
rm profilegc.log 2>&1 /dev/null
